keys:
  - &user_violet age14znucymclds0v2sqagnz9m6ptemq9uhqrdr5gtjqzhemu2kdn9rsxcq0ep
  - &host_liella age17l7dkuhs6y8zqahemjqq4hcrqupd028lelhd437m4m9f7ld3xg2qqm93rs
  - &host_quartz age1fnm9yafdq8lfmqxgwh5qn282ukmdxuyxzljdsurqvcgeug22kdrshnpuns
creation_rules:
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          - *user_violet
          - *host_liella
          - *host_quartz
