keys:
  - &admin_violet age14znucymclds0v2sqagnz9m6ptemq9uhqrdr5gtjqzhemu2kdn9rsxcq0ep
  - &host_liella age1nd0gj46sj82uqnp2a3a5sk5fsdyks8k3ye9dry43nc622dt3cc6q2xuyyw
  - &host_aqours age10katlmf70gx4knt5w6w6z6a0ary74gfxnvuydq9gpd3mlvrhx35sr2csyr
  - &user_violet age1wsyj3cgxa94fgcm8ylrkkan4py9e8pxh69t4q7aj45h6y9w98dzqr38hmy
creation_rules:
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          - *admin_violet
          - *host_liella
          - *host_aqours
  - path_regex: secrets/violet\.yaml$
    key_groups:
      - age:
          - *admin_violet
          - *user_violet
